<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Jadwal Inspeksi Mobile Tower</title>

    <style>
        /* ---------- PAGE & BODY ---------- */
        @page {
            margin: 15mm 10mm;
        }

        /* top/bot 15 mm, side 10 mm */
        body {
            font-family: Arial, sans-serif;
            font-size: 9px;
            margin: 0;
        }

        /* ---------- LAYOUT HELPERS ---------- */
        .container {
            padding: 10px;
        }

        .title {
            text-align: center;
            font-weight: bold;
            font-size: 1em;
            margin: 10px 0;
        }

        .subtitle {
            text-align: left;
            margin-bottom: 10px;
            font-size: 11px;
        }

        /* ---------- TABLE ---------- */
        table {
            width: 100%;
            border-collapse: collapse;
            table-layout: fixed;
            font-size: 1em;
        }

        th,
        td {
            border: 1px solid #000;
            padding: 3px;
            text-align: center;
            vertical-align: middle;
            word-wrap: break-word;
        }

        th {
            background-color: #0c0c64;
            color: #fff;
            font-size: 1em;
        }

        .dataContent {
            font-size: 1em;
        }

        .text-left {
            text-align: left;
        }

        /* ---------- HEADER IMAGE ---------- */
        img.logo {
            width: 100%;
            height: auto;
        }

        /* ---------- FOOTER ---------- */
        footer {
            position: fixed;
            bottom: 0;
            left: 0;
            right: 0;
            height: 20px;
            text-align: center;
            font-size: 9px;
            color: #555;
        }

        .footer-content {
            display: flex;
            justify-content: space-between;
            padding: 0 10px;
            margin: 1em;
        }
    </style>
</head>

<body>
    <div class="container">
        {{-- ---------- HEADER IMAGE (optional) ---------- --}}
        <table style="border-collapse:collapse; margin-bottom:5px;">
            <tr>
                <td style="border:none; padding:0;">
                    {{-- Make sure the file exists in public/images --}}
                    <img src="{{ public_path('images/header_ppa.jpg') }}" alt="Header Image" class="logo">
                </td>
            </tr>
        </table>

        {{-- ---------- TITLE & META ---------- --}}
        <div class="title">FORM JADWAL INSPEKSI MOBILE TOWER</div>

        <table style="width:100%; margin-bottom:10px; border-collapse:collapse;">
            <tr>
                <td style="text-align:left; border:none; font-weight:bold;">
                    Periode : <span style="font-weight:normal;">{{ $periodeLabel }}</span>

                </td>

                <td style="text-align:right; border:none; font-weight:bold;">
                    PPA-{{ strtoupper($site) }}-F-COE-02G
                </td>
            </tr>
        </table>

        {{-- ---------- DATA TABLE ---------- --}}
        <table>
            <thead>
                <tr>
                    <th style="width: 5%;">No</th>
                    <th style="width: 25%;">Mobile tower Code</th>
                    <th style="width: 20%;">Schedule Inspection</th>
                    <th style="width: 20%;">Actual Inspection</th>
                </tr>
            </thead>

            <tbody>
                @forelse ($schedules as $row)
                    <tr class="dataContent">
                        <td>{{ $loop->iteration }}</td>
                        <td>{{ $row->inventory_number }}</td>
                        <td>{{ \Carbon\Carbon::parse($row->tanggal_inspection)->format('d M Y') }}</td>
                        <td>
                            {{ $row->actual_inspection ? \Carbon\Carbon::parse($row->actual_inspection)->format('d M Y') : '-' }}
                        </td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="4">No data</td>
                    </tr>
                @endforelse
            </tbody>
        </table>
    </div>

    {{-- ---------- FOOTER ---------- --}}
    <footer>
        <div class="footer-content">
            <div>Generated by ITPORTAL | {{ now()->format('d M Y') }}</div>
        </div>
    </footer>
</body>

</html>